package com.promevity.medai.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Outbound payload returned by {@code POST /api/diagnose/{patientId}}.
 *
 * <p>Bundles the full diagnostic pipeline result so that API consumers
 * (mobile app, clinician dashboard) receive structured data alongside
 * the patient-friendly LLM explanation.
 *
 * @param patientId              Neo4j node ID of the patient
 * @param detectedSymptoms       Symptom names extracted from the free text
 * @param diseaseName            Highest-probability disease from the Bayesian network
 * @param probabilityPercentage  Probability score (0–100)
 * @param explanation            Patient-friendly explanation generated by the LLM
 */
public record DiagnoseResponse(

        @JsonProperty("patientId")
        String patientId,

        @JsonProperty("detectedSymptoms")
        List<String> detectedSymptoms,

        @JsonProperty("diseaseName")
        String diseaseName,

        @JsonProperty("probabilityPercentage")
        double probabilityPercentage,

        @JsonProperty("explanation")
        String explanation

) {}
